spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/dealership
    username: dealership
    password: dealership

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc.datasource: DEBUG